
package CatalogueUI;

import Data.TextAccess;
import GUI.LoginUI;
import ProductCatalogue.CalculateDiscount;
import ProductCatalogue.Catalogue;
import ProductCatalogue.CatalogueItems;
import java.awt.print.PrinterJob;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.JTable.PrintMode;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;


public class ProductCatalogueUI extends javax.swing.JFrame {
    public static String cID, cDescription, cTheme;
    DefaultTableModel model, model2, model3, model4; 
    public ProductCatalogueUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel)jTable1.getModel();
        TextAccess ta = new TextAccess();
        ta.setFileName("catalogue.txt");
        Object rowData[] = new Object[4];
        ArrayList<String> content = ta.readAll();
        for(int counter = 0; counter < content.size(); counter++){
            String[] split = content.get(counter).split("\\|");
            rowData[0] = split[0];
            rowData[1] = split[1];
            rowData[2] = split[2];
            rowData[3] = split[3];
            model.addRow(rowData); 
        }   
        model2 = (DefaultTableModel)jTable2.getModel();
        TextAccess ta2 = new TextAccess();
        ta2.setFileName("product.txt");
        Object rowData2[] = new Object[9];
        ArrayList<String> content2 = ta2.readAll();
        for(int counter = 0; counter < content2.size(); counter++){
            String[] split2 = content2.get(counter).split("\\|");
            rowData2[1] = split2[0];
            rowData2[2] = split2[1];
            rowData2[3] = split2[2];
            rowData2[4] = split2[3];
            rowData2[5] = split2[4];
            rowData2[6] = split2[5];
            rowData2[7] = split2[6];
            rowData2[8] = split2[7];
            model2.addRow(rowData2);  
        
        }  
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblMin1 = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        lblAddProduct1 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        openCatBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        recentLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        createPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCNames = new javax.swing.JTextField();
        txtCDescript = new javax.swing.JTextField();
        txtCTheme = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblMin2 = new javax.swing.JLabel();
        lblClose2 = new javax.swing.JLabel();
        lblAddProduct2 = new javax.swing.JLabel();
        selectProductPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblAddProduct = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        selectAllBtn = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        selectDoneBtn = new javax.swing.JButton();
        jSearchText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        catalogueListPanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblAddProduct7 = new javax.swing.JLabel();
        lblMin7 = new javax.swing.JLabel();
        lblClose7 = new javax.swing.JLabel();
        printBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        discountBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        discountPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblAddProduct8 = new javax.swing.JLabel();
        discountDoneBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        discountCancelBtn = new javax.swing.JButton();
        modifyPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAddProduct3 = new javax.swing.JLabel();
        lblMin3 = new javax.swing.JLabel();
        lblClose3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        selectDoneBtn1 = new javax.swing.JButton();
        jSearchText1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        menuPanel.setBackground(new java.awt.Color(255, 236, 139));

        jPanel5.setBackground(new java.awt.Color(37, 116, 169));

        lblMin1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMin1.setForeground(new java.awt.Color(232, 236, 241));
        lblMin1.setText("-");
        lblMin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMin1MouseClicked(evt);
            }
        });

        lblClose1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(232, 236, 241));
        lblClose1.setText("X");
        lblClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });

        lblAddProduct1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct1.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct1.setText("Catalogue Management");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(lblAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(lblMin1)
                .addGap(29, 29, 29)
                .addComponent(lblClose1)
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(426, 426, 426))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAddProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createBtn.setText("Create New Catalogue");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        openCatBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        openCatBtn.setText("Open");
        openCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCatBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        recentLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recentLabel.setText("Product Catalogues");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CATALOGUE NAME", "DESCRIPTION", "THEME"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(recentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(615, 615, 615))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(openCatBtn)
                        .addGap(29, 29, 29))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(recentLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openCatBtn)
                .addGap(50, 50, 50)
                .addComponent(backBtn)
                .addGap(22, 22, 22))
        );

        getContentPane().add(menuPanel, "card2");

        createPanel.setBackground(new java.awt.Color(255, 236, 139));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Catalogue Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Description:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Theme:");

        txtCNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNamesActionPerformed(evt);
            }
        });

        txtCDescript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCDescriptActionPerformed(evt);
            }
        });

        txtCTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCThemeActionPerformed(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        backBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(37, 116, 169));

        lblMin2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMin2.setForeground(new java.awt.Color(232, 236, 241));
        lblMin2.setText("-");
        lblMin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMin2MouseClicked(evt);
            }
        });

        lblClose2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblClose2.setForeground(new java.awt.Color(232, 236, 241));
        lblClose2.setText("X");
        lblClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose2MouseClicked(evt);
            }
        });

        lblAddProduct2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct2.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct2.setText("Create New Catalogue");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(lblAddProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(lblMin2)
                .addGap(26, 26, 26)
                .addComponent(lblClose2)
                .addGap(46, 46, 46))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(426, 426, 426))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAddProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(94, 94, 94)))
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCDescript)
                    .addComponent(txtCTheme)
                    .addComponent(txtCNames))
                .addGap(114, 114, 114))
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(backBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNames, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCDescript, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextBtn))
                .addGap(48, 48, 48))
        );

        getContentPane().add(createPanel, "card3");

        selectProductPanel.setBackground(new java.awt.Color(255, 236, 139));

        jPanel2.setBackground(new java.awt.Color(37, 116, 169));

        lblAddProduct.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct.setText("Select Product");

        lblMin.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMin.setForeground(new java.awt.Color(232, 236, 241));
        lblMin.setText("-");
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(232, 236, 241));
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(lblMin)
                .addGap(28, 28, 28)
                .addComponent(lblClose)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "NAME", "BRAND", "DESCRIPT", "QTY", "RETAIL", "SUPPLIER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        selectAllBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectAllBtn.setText("Select All");
        selectAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllBtnActionPerformed(evt);
            }
        });

        backBtn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn3.setText("Back");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });

        selectDoneBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectDoneBtn.setText("Done");
        selectDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDoneBtnActionPerformed(evt);
            }
        });

        jSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchTextActionPerformed(evt);
            }
        });
        jSearchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSearchTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchTextKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Search:");

        javax.swing.GroupLayout selectProductPanelLayout = new javax.swing.GroupLayout(selectProductPanel);
        selectProductPanel.setLayout(selectProductPanelLayout);
        selectProductPanelLayout.setHorizontalGroup(
            selectProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(selectProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(selectProductPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectDoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(selectProductPanelLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(selectAllBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectProductPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        selectProductPanelLayout.setVerticalGroup(
            selectProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectProductPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectAllBtn)
                .addGroup(selectProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectProductPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(selectProductPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectDoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(selectProductPanel, "card4");

        catalogueListPanel.setBackground(new java.awt.Color(255, 236, 139));

        jPanel10.setBackground(new java.awt.Color(37, 116, 169));

        lblAddProduct7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct7.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct7.setText("Product Catalogue");

        lblMin7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMin7.setForeground(new java.awt.Color(232, 236, 241));
        lblMin7.setText("-");
        lblMin7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMin7MouseClicked(evt);
            }
        });

        lblClose7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblClose7.setForeground(new java.awt.Color(232, 236, 241));
        lblClose7.setText("X");
        lblClose7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(lblAddProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(lblMin7)
                .addGap(26, 26, 26)
                .addComponent(lblClose7)
                .addGap(40, 40, 40))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        printBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        returnBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnBtn.setText("Return ");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "NAME", "BRAND", "DESCRIPT", "QTY", "RETAIL_P", "SUPPLIER", "CATEGORY", "DSICOUNT_P"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(18);
            jTable3.getColumnModel().getColumn(9).setResizable(false);
        }

        discountBtn.setText("Add Discount");
        discountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountBtnActionPerformed(evt);
            }
        });

        modifyBtn.setText("Modify");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogueListPanelLayout = new javax.swing.GroupLayout(catalogueListPanel);
        catalogueListPanel.setLayout(catalogueListPanelLayout);
        catalogueListPanelLayout.setHorizontalGroup(
            catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(catalogueListPanelLayout.createSequentialGroup()
                .addGroup(catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catalogueListPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(catalogueListPanelLayout.createSequentialGroup()
                                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(450, 450, 450)
                                .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(catalogueListPanelLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(discountBtn)
                        .addGap(26, 26, 26)
                        .addComponent(modifyBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catalogueListPanelLayout.setVerticalGroup(
            catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogueListPanelLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountBtn)
                    .addComponent(modifyBtn))
                .addGap(18, 18, 18)
                .addGroup(catalogueListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(returnBtn))
                .addGap(14, 14, 14))
        );

        getContentPane().add(catalogueListPanel, "card5");

        discountPanel.setBackground(new java.awt.Color(255, 236, 139));

        jPanel11.setBackground(new java.awt.Color(37, 116, 169));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        lblAddProduct8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct8.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct8.setText("Add Discount");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(lblAddProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblAddProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        discountDoneBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discountDoneBtn.setText("Done");
        discountDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountDoneBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Retail Price Discount by:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amount", "Percentage" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Please Enter Discount Value:");

        discountCancelBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discountCancelBtn.setText("Cancel");
        discountCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountPanelLayout = new javax.swing.GroupLayout(discountPanel);
        discountPanel.setLayout(discountPanelLayout);
        discountPanelLayout.setHorizontalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discountPanelLayout.createSequentialGroup()
                        .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(discountPanelLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(discountDoneBtn)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)))
                        .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(discountPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(discountCancelBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        discountPanelLayout.setVerticalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addComponent(discountDoneBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(discountCancelBtn)
                .addGap(48, 48, 48))
        );

        getContentPane().add(discountPanel, "card6");

        modifyPanel.setBackground(new java.awt.Color(255, 236, 139));

        jPanel3.setBackground(new java.awt.Color(37, 116, 169));

        lblAddProduct3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblAddProduct3.setForeground(new java.awt.Color(232, 236, 241));
        lblAddProduct3.setText("Modify Product");

        lblMin3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMin3.setForeground(new java.awt.Color(232, 236, 241));
        lblMin3.setText("-");
        lblMin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMin3MouseClicked(evt);
            }
        });

        lblClose3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblClose3.setForeground(new java.awt.Color(232, 236, 241));
        lblClose3.setText("X");
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(lblMin3)
                .addGap(28, 28, 28)
                .addComponent(lblClose3)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblAddProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "NAME", "BRAND", "DESCRIPT", "QTY", "RETAIL", "SUPPLIER", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        selectDoneBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectDoneBtn1.setText("Done");
        selectDoneBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDoneBtn1ActionPerformed(evt);
            }
        });

        jSearchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchText1ActionPerformed(evt);
            }
        });
        jSearchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSearchText1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchText1KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Search:");

        javax.swing.GroupLayout modifyPanelLayout = new javax.swing.GroupLayout(modifyPanel);
        modifyPanel.setLayout(modifyPanelLayout);
        modifyPanelLayout.setHorizontalGroup(
            modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(modifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSearchText1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPanelLayout.createSequentialGroup()
                        .addComponent(selectDoneBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        modifyPanelLayout.setVerticalGroup(
            modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearchText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectDoneBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(modifyPanel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        createPanel.setVisible(true);
        menuPanel.setVisible(false);
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        System.out.println("Row number is: " +jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        selectProductPanel.setVisible(true);
        createPanel.setVisible(false);
        Catalogue ca = new Catalogue(); 
        cDescription = txtCDescript.getText().trim();
        cTheme = txtCTheme.getText().trim();
        ca.setcName(txtCNames.getText().trim());
        ca.setcDescription(cDescription);
        ca.setcTheme(cTheme);
        cID = ca.create();
        


    }//GEN-LAST:event_nextBtnActionPerformed

    private void txtCNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNamesActionPerformed

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblClose1MouseClicked

    private void openCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCatBtnActionPerformed

        int row = jTable1.getSelectedRow();
        cID = (String)model.getValueAt(row, 0);
        cDescription = (String)model.getValueAt(row, 2);
        cTheme = (String)model.getValueAt(row, 3);
        TextAccess ta = new TextAccess();
        ta.setFileName(cID +".txt");
        model3 = (DefaultTableModel)jTable3.getModel();
        Object rowData3[] = new Object[10];
        ArrayList<String> content3 = ta.readAll();
        for(int counter = 0; counter < content3.size(); counter++){
            String[] split3 = content3.get(counter).split("\\|");
            rowData3[1] = split3[0];
            rowData3[2] = split3[1];
            rowData3[3] = split3[2];
            rowData3[4] = split3[3];
            rowData3[5] = split3[4];
            rowData3[6] = split3[5];
            rowData3[7] = split3[6];
            rowData3[8] = split3[7];
            rowData3[9] = split3[5]; 
            model3.addRow(rowData3);
        } 
        catalogueListPanel.setVisible(true);
        menuPanel.setVisible(false);
        
                
    }//GEN-LAST:event_openCatBtnActionPerformed

    private void lblClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_lblClose2MouseClicked

    private void txtCDescriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCDescriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCDescriptActionPerformed

    private void txtCThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCThemeActionPerformed

    private void selectDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDoneBtnActionPerformed

        final Formatter x;
        try {
            x = new Formatter(cID + ".txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ProductCatalogueUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        CatalogueItems ci = new CatalogueItems();
        for (int row = 0; row < jTable2.getRowCount(); row++){
            if(jTable2.getModel().getValueAt(row, 0) == Boolean.TRUE){
                ci.setpID(Integer.valueOf((String)jTable2.getModel().getValueAt(row, 1)));
                ci.setpName(String.valueOf(jTable2.getModel().getValueAt(row, 2)));
                ci.setpBrand(String.valueOf(jTable2.getModel().getValueAt(row, 3)));
                ci.setpDescription(String.valueOf(jTable2.getModel().getValueAt(row, 4)));
                ci.setpQuantity(Integer.valueOf((String)jTable2.getModel().getValueAt(row, 5)));
                ci.setpRetailPrice(Float.valueOf((String)jTable2.getModel().getValueAt(row, 6)));
                ci.setpSupplierInfo(String.valueOf(jTable2.getModel().getValueAt(row, 7)));
                ci.setpCategory(String.valueOf(jTable2.getModel().getValueAt(row, 8)));
                ci.create(cID);
            }else {
                continue;
            }
        }
            
        model3 = (DefaultTableModel)jTable3.getModel();
        TextAccess ta3 = new TextAccess();
        ta3.setFileName(cID + ".txt");
        Object rowData3[] = new Object[10];
        ArrayList<String> content3 = ta3.readAll();
        for(int counter = 0; counter < content3.size(); counter++){
            String[] split3 = content3.get(counter).split("\\|");
            rowData3[1] = split3[0];
            rowData3[2] = split3[1];
            rowData3[3] = split3[2];
            rowData3[4] = split3[3];
            rowData3[5] = split3[4];
            rowData3[6] = split3[5];
            rowData3[7] = split3[6];
            rowData3[8] = split3[7];
            rowData3[9] = split3[5];
            model3.addRow(rowData3);
        }      
        catalogueListPanel.setVisible(true);
        selectProductPanel.setVisible(false); 
    }//GEN-LAST:event_selectDoneBtnActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        createPanel.setVisible(true);
        selectProductPanel.setVisible(false);
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblClose7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblClose7MouseClicked

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        createPanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        MessageFormat header = new MessageFormat(cTheme + "-" + cDescription);
        MessageFormat footer = new MessageFormat("Product Catalogue generated by: " + System.getProperty("user.name") + ", " + new Date());
        try{
            jTable3.print(JTable.PrintMode.FIT_WIDTH, header,footer); 
        }catch(java.awt.print.PrinterException e){
            System.out.println("Unable to generate PDF");
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void discountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountBtnActionPerformed
        catalogueListPanel.setVisible(false);
        discountPanel.setVisible(true);
     
    }//GEN-LAST:event_discountBtnActionPerformed

    private void discountDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountDoneBtnActionPerformed
        double discount=0, retail=0; 
        String newdata = null;
        CalculateDiscount dis = new CalculateDiscount();
        TextAccess ta = new TextAccess();
        ta.setFileName(cID+ ".txt");
        ArrayList<String> data = ta.readAll(); 
        for (int counter = 0; counter < data.size(); counter ++){
            String[] split = data.get(counter).split("\\|");
            retail = Double.valueOf(split[5]);
            dis.setRetail(retail);
            if(jComboBox1.getSelectedIndex() == 0){
                discount = dis.discountAmount(Double.valueOf(jTextField1.getText().trim())); 
            }else{
                discount = dis.discountPercentage(Double.valueOf(jTextField1.getText().trim())); 
            }
            jTable3.getModel().setValueAt(discount, counter, 9);
        }

        catalogueListPanel.setVisible(true);
        discountPanel.setVisible(false);
        
    }//GEN-LAST:event_discountDoneBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblMin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMin1MouseClicked
       this.setState(LoginUI.ICONIFIED);
    }//GEN-LAST:event_lblMin1MouseClicked

    private void lblMin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMin2MouseClicked
        this.setState(LoginUI.ICONIFIED);
    }//GEN-LAST:event_lblMin2MouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
       this.setState(LoginUI.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMin7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMin7MouseClicked
        this.setState(LoginUI.ICONIFIED);
    }//GEN-LAST:event_lblMin7MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseClicked

    private void discountCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountCancelBtnActionPerformed
        catalogueListPanel.setVisible(true);
        discountPanel.setVisible(false);
    }//GEN-LAST:event_discountCancelBtnActionPerformed

    private void jSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchTextActionPerformed

    private void jSearchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchTextKeyReleased
        model2 = (DefaultTableModel)jTable2.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model2);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jSearchText.getText()));
    }//GEN-LAST:event_jSearchTextKeyReleased

    private void jSearchTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchTextKeyPressed

    }//GEN-LAST:event_jSearchTextKeyPressed
 
    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        ((DefaultTableModel) jTable3.getModel()).setRowCount(0); 
        modifyBtn.setVisible(false);
        model4 = (DefaultTableModel)jTable4.getModel(); 
        TextAccess ta2 = new TextAccess();
        ta2.setFileName("product.txt");
        Object rowData2[] = new Object[9];
        ArrayList<String> content2 = ta2.readAll();
        for(int counter = 0; counter < content2.size(); counter++){
            String[] split2 = content2.get(counter).split("\\|");
            rowData2[1] = split2[0];
            rowData2[2] = split2[1];
            rowData2[3] = split2[2];
            rowData2[4] = split2[3];
            rowData2[5] = split2[4];
            rowData2[6] = split2[5];
            rowData2[7] = split2[6];
            rowData2[8] = split2[7];
            model4.addRow(rowData2);  
        
        }   
        
        TextAccess ta = new TextAccess();
        ta.setFileName(cID+ ".txt");
        ArrayList<String> content = ta.readAll();
        for(int i = 0; i < content.size(); i++){
            String[] split = content.get(i).split("\\|");
            for (int row = 0; row < jTable4.getRowCount(); row++){
                if (split[0].equals(jTable4.getModel().getValueAt(row, 1))){
                    jTable4.getModel().setValueAt(true, row, 0);
                }else{
                    continue;
                }
            }
        }
        catalogueListPanel.setVisible(false);
        modifyPanel.setVisible(true);
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void lblMin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMin3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMin3MouseClicked

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClose3MouseClicked

    private void selectDoneBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDoneBtn1ActionPerformed
        try { 
            new PrintWriter(cID + ".txt").close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ProductCatalogueUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        CatalogueItems ci = new CatalogueItems();
        TextAccess ta = new TextAccess();
        for (int row = 0; row < jTable4.getRowCount(); row++){
            if(jTable4.getModel().getValueAt(row, 0) == Boolean.TRUE){
                ci.setpID(Integer.valueOf((String)jTable4.getModel().getValueAt(row, 1)));
                ci.setpName(String.valueOf(jTable4.getModel().getValueAt(row, 2)));
                ci.setpBrand(String.valueOf(jTable4.getModel().getValueAt(row, 3)));
                ci.setpDescription(String.valueOf(jTable4.getModel().getValueAt(row, 4)));
                ci.setpQuantity(Integer.valueOf((String)jTable4.getModel().getValueAt(row, 5)));
                ci.setpRetailPrice(Float.valueOf((String)jTable4.getModel().getValueAt(row, 6)));
                ci.setpSupplierInfo(String.valueOf(jTable4.getModel().getValueAt(row, 7)));
                ci.setpCategory(String.valueOf(jTable4.getModel().getValueAt(row, 8))); 
                ci.create(cID);
            }else {
                continue;
            };
            
        }
        model3 = (DefaultTableModel)jTable3.getModel();
        TextAccess ta3 = new TextAccess();
        ta3.setFileName(cID + ".txt");
        Object rowData3[] = new Object[10];
        ArrayList<String> content3 = ta3.readAll();
        for(int counter = 0; counter < content3.size(); counter++){
            String[] split3 = content3.get(counter).split("\\|");
            rowData3[1] = split3[0];
            rowData3[2] = split3[1];
            rowData3[3] = split3[2];
            rowData3[4] = split3[3];
            rowData3[5] = split3[4];
            rowData3[6] = split3[5];
            rowData3[7] = split3[6];
            rowData3[8] = split3[7];
            rowData3[9] = split3[5];
            model3.addRow(rowData3);
        }      
        modifyPanel.setVisible(false);
        catalogueListPanel.setVisible(true);
    }//GEN-LAST:event_selectDoneBtn1ActionPerformed

    private void jSearchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchText1ActionPerformed

    private void jSearchText1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchText1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchText1KeyPressed

    private void jSearchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchText1KeyReleased
        model4 = (DefaultTableModel)jTable4.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model4);
        jTable4.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jSearchText1.getText()));
    }//GEN-LAST:event_jSearchText1KeyReleased

    private void selectAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllBtnActionPerformed
        Object rowData2[] = new Object[9];
        for (int i = 0; i < jTable2.getRowCount(); i++){
            if(jTable2.getModel().getValueAt(i, 0) == Boolean.FALSE){
                jTable2.getModel().setValueAt(true, i, 0);
            }else{
                jTable2.getModel().setValueAt(false, i, 0);
            }

        }
    }//GEN-LAST:event_selectAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductCatalogueUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductCatalogueUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductCatalogueUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductCatalogueUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductCatalogueUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn3;
    private javax.swing.JPanel catalogueListPanel;
    private javax.swing.JButton createBtn;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton discountBtn;
    private javax.swing.JButton discountCancelBtn;
    private javax.swing.JButton discountDoneBtn;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jSearchText;
    private javax.swing.JTextField jSearchText1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblAddProduct1;
    private javax.swing.JLabel lblAddProduct2;
    private javax.swing.JLabel lblAddProduct3;
    private javax.swing.JLabel lblAddProduct7;
    private javax.swing.JLabel lblAddProduct8;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblClose2;
    private javax.swing.JLabel lblClose3;
    private javax.swing.JLabel lblClose7;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblMin1;
    private javax.swing.JLabel lblMin2;
    private javax.swing.JLabel lblMin3;
    private javax.swing.JLabel lblMin7;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JPanel modifyPanel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton openCatBtn;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel recentLabel;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton selectAllBtn;
    private javax.swing.JButton selectDoneBtn;
    private javax.swing.JButton selectDoneBtn1;
    private javax.swing.JPanel selectProductPanel;
    private javax.swing.JTextField txtCDescript;
    private javax.swing.JTextField txtCNames;
    private javax.swing.JTextField txtCTheme;
    // End of variables declaration//GEN-END:variables
}
